# © Copyright 2019 Micro Focus or one of its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  "This template deploys a Micro Focus PlateSpin Migrate server stack into a new VPC.
  **WARNING** This template creates EC2 instances and related resources. You
  will be billed for the AWS resources used if you create a stack from this
  template. License: Apache 2.0 (Please do not remove) Feb 20, 2019. Micro Focus
  PlateSpin is licensed separately, please review the terms and
  conditions here (https://www.microfocus.com/about/legal/) for further details.
  (qs-1pb7ojm39)"
Metadata:
  Version: v1.0
  Comments: Generated by the PlateSpin Migrate Quick Start team
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: License agreement
        Parameters:
          - LicenseAgreement
      - Label:
          default: VPC Network configuration
        Parameters:
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
      - Label:
          default: PlateSpin Migrate server configuration
        Parameters:
          - MigrateServerVersion
          - KeyPairName
          - MigrateServerInstanceType
          - AssignElasticIP
          - ReplicationAccessCIDR
          - ManagementAccessCIDR
          - TargetWorkloadsInterconnectCIDR
          - SNSTopicMailID
          - MigrateServerHostname
          - MigrateAdminUsername
          - MigrateAdminPassword
          - MigrateAdminConfirmPassword
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      MigrateServerVersion:
        default: Migrate server version
      AssignElasticIP:
        default: Assign persistent public IP address
      AvailabilityZones:
        default: Availability Zones
      KeyPairName:
        default: Key pair name
      LicenseAgreement:
        default: License agreement
      ManagementAccessCIDR:
        default: Management access CIDR
      MigrateAdminConfirmPassword:
        default: Re-enter the admin password
      MigrateAdminPassword:
        default: Admin password
      MigrateAdminUsername:
        default: Admin username
      MigrateServerHostname:
        default: Hostname
      MigrateServerInstanceType:
        default: Instance type
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      ReplicationAccessCIDR:
        default: Replication access CIDR
      SNSTopicMailID:
        default: Email ID
      TargetWorkloadsInterconnectCIDR:
        default: Target workloads interconnect CIDR
      VPCCIDR:
        default: VPC CIDR
Parameters:
  MigrateServerVersion:
    Description: >-
      The version of PlateSpin Migrate server to be provisioned.
    Type: String
    AllowedValues:
      - '2019.11'
      - '2020.2'
    Default: '2020.2'
  AssignElasticIP:
    Description: >-
      Choose 'No' to prevent accessing the PlateSpin Migrate server directly from the Internet.
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  AvailabilityZones:
    Description: The list of Availability Zones to use for the subnets in the VPC. Select any two. This Quick Start uses the first two zones from your selected list.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  KeyPairName:
    Description: >-
      The name of an existing EC2 key pair, which allows you to securely connect to your instance after it launches.
    Type: 'AWS::EC2::KeyPair::KeyName'
    AllowedPattern: .+
    ConstraintDescription: Must be the name of an existing EC2 key pair.
  LicenseAgreement:
    Description: >-
      I have read and agree to the license terms for Micro Focus PlateSpin Migrate
      (https://www.microfocus.com/licensing/eula/netiq/platespin/platespin_migrate_2019_english.pdf).
    Type: String
    Default: '-'
    AllowedValues:
      - I agree
      - '-'
    ConstraintDescription: must answer 'I agree'
  ManagementAccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: >-
      The CIDR IP range that is permitted RDP (3389/TCP) and HTTPS (443/TCP) access to the PlateSpin Migrate server, and RDP (3389/TCP) or SSH (22/TCP) access to the migrated workloads in the production or test environment, for administrative purposes.
    Type: String
  MigrateAdminConfirmPassword:
    Description: >-
      The password confirmation for the PlateSpin Migrate server admin account.
    Type: String
    MinLength: '8'
    MaxLength: '32'
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    NoEcho: 'true'
  MigrateAdminPassword:
    Description: >-
      The password for the PlateSpin Migrate server admin account. It can contain 8 to 32 alphanumeric characters and symbols.
    Type: String
    MinLength: '8'
    MaxLength: '32'
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    NoEcho: 'true'
  MigrateAdminUsername:
    Description: The username for the PlateSpin Migrate server admin account. This name can contain 5 to 25 alphanumeric characters.
    Type: String
    Default: psadmin
    MinLength: '5'
    MaxLength: '25'
    AllowedPattern: '[a-zA-Z0-9]*'
  MigrateServerHostname:
    Description: >-
      The hostname (up to 15 characters) for your PlateSpin Migrate server. This name can contain alphanumeric characters and hyphens. It should start with a letter and should not end with a hyphen.
    Type: String
    Default: psmigrate
    MaxLength: '15'
    AllowedPattern: '^[a-zA-Z]|([a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$)'
    ConstraintDescription: >-
      Must begin with a letter, contain alphanumeric characters and hyphens, and can not end with a hyphen. Maximum length upto 15 characters.
  MigrateServerInstanceType:
    Description: The Amazon EC2 instance type for your PlateSpin Migrate server.
    Type: String
    Default: t3.large
    AllowedValues:
      - t3.large
      - t3.xlarge
      - m5.large
      - m5.xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  PrivateSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: The CIDR block for private subnet 1 located in Availability Zone 1
    Type: String
    Default: 10.0.0.0/19
  PrivateSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: The CIDR block for private subnet 2 located in Availability Zone 2
    Type: String
    Default: 10.0.32.0/19
  PublicSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: The CIDR block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
    Default: 10.0.128.0/20
  PublicSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: The CIDR block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String
    Default: 10.0.144.0/20
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers,
      lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-microfocus-platespin/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers,
      lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Type: String
  ReplicationAccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: >-
      The CIDR IP range that is permitted HTTPS (443/TCP) access to the PlateSpin Migrate server for agent registration, and source replication data traffic (3725/TCP) access to the replicating workloads in the cloud. This CIDR IP range must contain all source workloads to be migrated.
    Type: String
  SNSTopicMailID:
    Description: >-
      (Optional) The email ID to which AWS CloudWatch alarm notifications about the PlateSpin Migrate server will be sent.
    Type: String
    AllowedPattern: (?i)^None$|([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email ID.
    Default: None
  TargetWorkloadsInterconnectCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: >-
      The CIDR IP range that is permitted all-traffic (0-65535/UDP,TCP) access to migrated workloads in the production and test environment.
    Type: String
  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: >-
      The CIDR block for the VPC. This CIDR block must be in the form x.x.x.x/16-28.
    Type: String
    Default: 10.0.0.0/16
Rules:
  LicenseAgreementRule:
    Assertions:
      - Assert:
          'Fn::Contains':
            - - I agree
            - !Ref LicenseAgreement
        AssertDescription: User must agree to the terms of the license agreement.
  MigrateAdminPasswordMatchRule:
    Assertions:
      - Assert: !Equals
          - !Ref MigrateAdminPassword
          - !Ref MigrateAdminConfirmPassword
        AssertDescription: The PlateSpin Migrate Admin password values do not match.
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  AutoAssignEIP: !Equals
    - !Ref AssignElasticIP
    - 'Yes'
  GovCloudCondition: !Or
    - !Equals
      - !Ref 'AWS::Region'
      - us-gov-west-1
    - !Equals
      - !Ref 'AWS::Region'
      - us-gov-east-1
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join
          - ','
          - !Ref AvailabilityZones
        CreatePrivateSubnets: 'true'
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
  PlateSpinMigrateStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - >-
          https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/quickstart-platespin-template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        MigrateServerVersion: !Ref MigrateServerVersion
        AssignElasticIP: !Ref AssignElasticIP
        KeyPairName: !Ref KeyPairName
        LicenseAgreement: !Ref LicenseAgreement
        ManagementAccessCIDR: !Ref ManagementAccessCIDR
        MigrateAdminConfirmPassword: !Ref MigrateAdminConfirmPassword
        MigrateAdminPassword: !Ref MigrateAdminPassword
        MigrateAdminUsername: !Ref MigrateAdminUsername
        MigrateServerHostname: !Ref MigrateServerHostname
        MigrateServerInstanceType: !Ref MigrateServerInstanceType
        SubnetID: !If
          - AutoAssignEIP
          - !GetAtt VPCStack.Outputs.PublicSubnet1ID
          - !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        ReplicationAccessCIDR: !Ref ReplicationAccessCIDR
        SNSTopicMailID: !Ref SNSTopicMailID
        TargetWorkloadsInterconnectCIDR: !Ref TargetWorkloadsInterconnectCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
Outputs:
  MigrateServerPrivateURL:
    Description: The URL of the deployed PlateSpin Migrate server
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerPrivateURL
  MigrateServerPublicURL:
    Condition: AutoAssignEIP
    Description: The public URL of the deployed PlateSpin Migrate server
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerPublicURL
  MigrateServerPrivateIP:
    Description: The IP address of the deployed PlateSpin Migrate server instance
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerPrivateIP
  MigrateServerPublicIP:
    Condition: AutoAssignEIP
    Description: The IP address of the deployed PlateSpin Migrate server instance
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerPublicIP
  MigrateServerInstanceID:
    Description: The PlateSpin Migrate server EC2 instance ID
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerInstanceID
  MigrateServerLogGroupName:
    Description: The name of the CloudWatch log group
    Value: !GetAtt PlateSpinMigrateStack.Outputs.MigrateServerLogGroupName
